# Contains UML, code_coverage, dependency_checker
#UML
FROM ubuntu:22.04
WORKDIR /app
# COPY ./python/ /app
RUN apt-get update && apt-get upgrade -y
RUN apt install -y curl
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y git
RUN apt-get install -y graphviz
RUN pip3 install -r uml/requirements.txt

#code Coverage
RUN apt-get install -y \
    curl \
    wget \
    iputils-ping \
    dnsutils \
    git \
    && \
    rm -rf /var/lib/apt/lists/* \
    && pip install requests\
    && pip install coverage\
    && pip install pytest


#dependency_checker

RUN apt-get install -y \
    && \
    rm -rf /var/lib/apt/lists/*

