FROM frolvlad/alpine-python3

# Install necessary tools for networking
RUN apk update && \
    apk add --no-cache \
        curl \
        wget \
        iputils \
        bind-tools \
        git \
        && \
    rm -rf /var/cache/apk/*\
    && pip install requests\
    && pip install coverage\
    && pip install pytest

# Install python packages
# astroid==3.0.3
# dill==0.3.8
# gitdb==4.0.11
# GitPython==3.1.42
# isort==5.13.2
# lint==1.2.1
# mccabe==0.7.0
# platformdirs==4.2.0
# pylint==3.0.3
# smmap==5.0.1
# tomlkit==0.12.3


# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /usr/src/app

COPY ./code ./
#COPY ./received ./send
#COPY ./received ./send
#can't mount to a existing file in the container
#COPY ./received ./send
EXPOSE 8000

#CMD ["git","clone","https://github.com/nishad-dhuri-05/HiveLink.git"]
CMD ["python", "test.py"]