# Dockerfile for python code coverage
FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    iputils-ping \
    dnsutils \
    git \
    && \
    rm -rf /var/lib/apt/lists/* \
    && pip install requests\
    && pip install coverage\
    && pip install pytest

WORKDIR /app

COPY . .